[Content]
ExtraTrees=
    ../../cosign.pub:/usr/share/pki/containers/synthos.pub

[Content]
RemoveFiles=
    /usr/bin/chsh
    /usr/bin/lchsh
    /usr/lib/systemd/system/flatpak-add-fedora-repos.service
    /usr/share/applications/btop.desktop

VolatilePackages=
    systemd-container

Packages=
    bolt
    brightnessctl
    btop
    default-fonts
    default-fonts-core-emoji
    distrobox
    fastfetch
    flatpak
    generic-logos
    git-core
    glibc-all-langpacks
    glycin-thumbnailer
    gnome-disk-utility
    gnupg2-scdaemon
    google-noto-color-emoji-fonts
    google-noto-emoji-fonts
    gum
    hyfetch
    input-remapper
    just
    lshw
    nano-default-editor
    nm-connection-editor
    nmtui
    openrgb-udev-rules
    openssh-askpass
    orca
    pam-u2f
    pamu2fcfg
    playerctl
    steam-devices
    tailscale
    tesseract
    udiskie
    webp-pixbuf-loader
    wl-clipboard
    xdg-terminal-exec
    ykman

# FIXME: Remove once https://github.com/systemd/mkosi/pull/4390 is merged
[Build]
ToolsTreePackages=
    passwd
