[Distribution]
Repositories=terra

[Content]
Packages=
    cardwire
    cardwire-gui
    envision-nightly
    maple-fonts
    monado
    steam
    terra-wireplumber
    wivrn
    bazzite-portal
    xr-hardware
