[Distribution]
Repositories=terra

[Content]
Packages=
    asusctl
    bazzite-portal
    cardwire
    cardwire-gui
    dkms-xonedo-nightly
    envision-nightly
    inputplumber
    java-latest-openjdk # For SlimeVR
    maple-fonts
    monado
    powerstation
    ScopeBuddy
    scx-scheds
    scx-tools
    steam
    steamos-manager
    terra-wireplumber
    umu-launcher
    wivrn
    xr-hardware
