[Content]
Packages=
        bluedevil
        breeze-gtk
        dolphin
        flatpak-kcm
        kde-gtk-config
        kdeplasma-addons
        kgamma
        kinfocenter
        konsole
        kscreen
        ksshaskpass
        kwallet-pam
        ocean-sound-theme
        plasma-desktop
        plasma-drkonqi
        plasma-login-manager
        plasma-setup
        plasma-nm
        plasma-pa
        plasma-print-manager
        plasma-systemmonitor
        plasma-thunderbolt
        plasma-welcome
        plasma-workspace-wallpapers
        powerdevil
        spectacle
        xdg-desktop-portal-kde
